- 👋 Oi, eu sou @IgorDaniel182
- 👀 Eu estou interessado em me tornar desenvolvedor de sistemas e começar uma empresa com o objetivo de "trazer" crianças pobres ou com incapacidades para treina-las e fazer com que se tornem o que desejam futuramente e até influenciando a se interessarem pela área tecnologica.
- 🌱 Eu estou aprendendo a ser um desenvolvedor de sistemas.
- 💞️ Eu estou procurando colaborar me juntando a uma das empresas da Porto Digital.
- 📫 Como me encontrar? Me mandando mensagens no Linkedln: https://www.linkedin.com/in/igor-daniel-a73037211/ ou no meio e-mail: igordaniel1903@gmail.com
